### PR TITLE
A few issues in Powershell

### PR DESCRIPTION
**Pull request by MagneS**
Hi, I've made a few fixes for this to work OK in Powershell.  But I'm a complete novice using Github, so if I don't do this correct, just let me know.

Thanks for an exellent API cmdLet.

### CODE REVIEW

**Comment by franklupo** [comment]
Hi,
why extjs?

best regards

**Comment by franklupo** [comment]
Whi $MigrationType add blank value [ValidateSet('secure','insecure','')]?

**Comment by MagneS** [comment]
Hi,
I don't quite recall why I added that one..
I will do some testing and get back to you on that one.

I amended the code back in version 7.0.0.0 when I started using it, and
didn't think more about it. But recently I've changed my computer and
reinstalled everything and then I realized my changes also would benefit
others.

regards

Magne


man. 7. feb. 2022 kl. 08:40 skrev Daniele Corsini ***@***.***

**Comment by MagneS** [comment]
Hi,
I've now tested my normal cases with [ValidateSet('secure','insecure')]
and all work OK.

So I suspect I had some issues with node startup back when I made the
changes the first time.

\Magne


man. 7. feb. 2022 kl. 08:40 skrev Daniele Corsini ***@***.***

**Comment by MagneS** [comment]
Hi,
I think I used ExtJs back on V6.1 or so as I couldn't get it to work with
json. But I've tested OK with json now, so all ExtJs should be removed (and
replaced with json where needed)
So should I make a new branch/pull request, or can you use only the bits
that are OK ?
It is reaffirming to have such a good code review  as I haven't really done
so much programming the last 10 years.

\Magne


man. 7. feb. 2022 kl. 08:23 skrev Daniele Corsini ***@***.***

**Comment by franklupo** [comment]
> Hi, I think I used ExtJs back on V6.1 or so as I couldn't get it to work with json. But I've tested OK with json now, so all ExtJs should be removed (and replaced with json where needed) So should I make a new branch/pull request, or can you use only the bits that are OK ? It is reaffirming to have such a good code review as I haven't really done so much programming the last 10 years.

Ok create new pull request.

best regards

**Comment by franklupo** [comment]
By default the response is 'json'. 
Why do you have to specify?

**Pull request closed without merging**
